services:
  - type: web
    name: likevn-order-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k uvicorn.workers.UvicornWorker app:app --bind 0.0.0.0:$PORT --timeout 180"
    branch: fltt
    autoDeploy: true
